services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: RepairShop
      MYSQL_USER: RepairUser
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    # (this is just an example, not intended to be a production configuration)
